### ISSUE TITLE
Add these glyphs

### ISSUE THREAD

**Issue by cssobral2013** [indestructible-type/Renner#5]
S and s with cedilla (for Turkish), IJ and ij glyphs (for Dutch) and ŉ (for Afrikaans).

**Comment by fitojb** [comment]
What is the benefit of adding “ŉ” (U+0149)? It’s obsolete; it’s even been deprecated by Unicode.

**Comment by GitBruno** [comment]
Deprecated characters are discouraged to be used. However, such characters are retained in the standard indefinitely. You would still need them if you want to render a historical text. (Think of classic Afrikaans books for example)

**Comment by fitojb** [comment]
@GitBruno Hmm, because apparently, typing a sequence of **’** and **n** is not an option. It is irrelevant that Unicode retains the character, because they don’t do so to maintain stability, but that doesn’t mean that encoding the pointless 0149 wasn’t a mistake in the first place. That’s why it’s deprecated.

>  Only those few characters which have been determined by the UTC to have serious architectural defects or which have been determined to cause significant implementation problems are ever deprecated.
—[Unicode Technical Report 44](http://www.unicode.org/reports/tr44/#Deprecation)

Any text including the character should be reencoded to exclude it.

**Comment by EwonRael** [comment]
There's no harm in making the font include those characters, regardless on your beliefs towards whether or not they should be included in unicode. If you don't think an obsolete character should be used then you don't have to use it, silly Billy.

That being said I don't have a functional computer right now so I really can't get around to adding them anytime soon. This is on my radar and to-do list though and will probably be included in the next release.

I love you all. I know this isn't the right forum for that kind of sentiment, but the community is the backbone of this kind of project.

**Comment by EwonRael** [comment]
Okay!

As of today Renner* 3.0 should have all of the requested characters.
